#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyKhachSan")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblChiTietPhieu(tblChiTietPhieu instance);
    partial void UpdatetblChiTietPhieu(tblChiTietPhieu instance);
    partial void DeletetblChiTietPhieu(tblChiTietPhieu instance);
    partial void InserttblDichVu(tblDichVu instance);
    partial void UpdatetblDichVu(tblDichVu instance);
    partial void DeletetblDichVu(tblDichVu instance);
    partial void InserttblDoDung(tblDoDung instance);
    partial void UpdatetblDoDung(tblDoDung instance);
    partial void DeletetblDoDung(tblDoDung instance);
    partial void InserttblKhach(tblKhach instance);
    partial void UpdatetblKhach(tblKhach instance);
    partial void DeletetblKhach(tblKhach instance);
    partial void InserttblPhieuThue(tblPhieuThue instance);
    partial void UpdatetblPhieuThue(tblPhieuThue instance);
    partial void DeletetblPhieuThue(tblPhieuThue instance);
    partial void InserttblPhong(tblPhong instance);
    partial void UpdatetblPhong(tblPhong instance);
    partial void DeletetblPhong(tblPhong instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::QuanLyKhachSan.Properties.Settings.Default.QuanLyKhachSanConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblChiTietPhieu> tblChiTietPhieus
		{
			get
			{
				return this.GetTable<tblChiTietPhieu>();
			}
		}
		
		public System.Data.Linq.Table<tblDichVu> tblDichVus
		{
			get
			{
				return this.GetTable<tblDichVu>();
			}
		}
		
		public System.Data.Linq.Table<tblDoDung> tblDoDungs
		{
			get
			{
				return this.GetTable<tblDoDung>();
			}
		}
		
		public System.Data.Linq.Table<tblKhach> tblKhaches
		{
			get
			{
				return this.GetTable<tblKhach>();
			}
		}
		
		public System.Data.Linq.Table<tblPhieuThue> tblPhieuThues
		{
			get
			{
				return this.GetTable<tblPhieuThue>();
			}
		}
		
		public System.Data.Linq.Table<tblPhong> tblPhongs
		{
			get
			{
				return this.GetTable<tblPhong>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietPhieu")]
	public partial class tblChiTietPhieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPhieuThue;
		
		private int _IDPhong;
		
		private int _IDDichVu;
		
		private int _IDDoDung;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _ThanhTien;
		
		private string _IDChiTietPhieu;
		
		private EntityRef<tblDichVu> _tblDichVu;
		
		private EntityRef<tblDoDung> _tblDoDung;
		
		private EntityRef<tblPhong> _tblPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPhieuThueChanging(int value);
    partial void OnIDPhieuThueChanged();
    partial void OnIDPhongChanging(int value);
    partial void OnIDPhongChanged();
    partial void OnIDDichVuChanging(int value);
    partial void OnIDDichVuChanged();
    partial void OnIDDoDungChanging(int value);
    partial void OnIDDoDungChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    partial void OnIDChiTietPhieuChanging(string value);
    partial void OnIDChiTietPhieuChanged();
    #endregion
		
		public tblChiTietPhieu()
		{
			this._tblDichVu = default(EntityRef<tblDichVu>);
			this._tblDoDung = default(EntityRef<tblDoDung>);
			this._tblPhong = default(EntityRef<tblPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhieuThue", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPhieuThue
		{
			get
			{
				return this._IDPhieuThue;
			}
			set
			{
				if ((this._IDPhieuThue != value))
				{
					this.OnIDPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._IDPhieuThue = value;
					this.SendPropertyChanged("IDPhieuThue");
					this.OnIDPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPhong
		{
			get
			{
				return this._IDPhong;
			}
			set
			{
				if ((this._IDPhong != value))
				{
					if (this._tblPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPhongChanging(value);
					this.SendPropertyChanging();
					this._IDPhong = value;
					this.SendPropertyChanged("IDPhong");
					this.OnIDPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDichVu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDichVu
		{
			get
			{
				return this._IDDichVu;
			}
			set
			{
				if ((this._IDDichVu != value))
				{
					if (this._tblDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDichVuChanging(value);
					this.SendPropertyChanging();
					this._IDDichVu = value;
					this.SendPropertyChanged("IDDichVu");
					this.OnIDDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDoDung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDoDung
		{
			get
			{
				return this._IDDoDung;
			}
			set
			{
				if ((this._IDDoDung != value))
				{
					if (this._tblDoDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDoDungChanging(value);
					this.SendPropertyChanging();
					this._IDDoDung = value;
					this.SendPropertyChanged("IDDoDung");
					this.OnIDDoDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDChiTietPhieu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDChiTietPhieu
		{
			get
			{
				return this._IDChiTietPhieu;
			}
			set
			{
				if ((this._IDChiTietPhieu != value))
				{
					this.OnIDChiTietPhieuChanging(value);
					this.SendPropertyChanging();
					this._IDChiTietPhieu = value;
					this.SendPropertyChanged("IDChiTietPhieu");
					this.OnIDChiTietPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDichVu_tblChiTietPhieu", Storage="_tblDichVu", ThisKey="IDDichVu", OtherKey="IDDichVu", IsForeignKey=true)]
		public tblDichVu tblDichVu
		{
			get
			{
				return this._tblDichVu.Entity;
			}
			set
			{
				tblDichVu previousValue = this._tblDichVu.Entity;
				if (((previousValue != value) 
							|| (this._tblDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDichVu.Entity = null;
						previousValue.tblChiTietPhieus.Remove(this);
					}
					this._tblDichVu.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieus.Add(this);
						this._IDDichVu = value.IDDichVu;
					}
					else
					{
						this._IDDichVu = default(int);
					}
					this.SendPropertyChanged("tblDichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDoDung_tblChiTietPhieu", Storage="_tblDoDung", ThisKey="IDDoDung", OtherKey="IDDoDung", IsForeignKey=true)]
		public tblDoDung tblDoDung
		{
			get
			{
				return this._tblDoDung.Entity;
			}
			set
			{
				tblDoDung previousValue = this._tblDoDung.Entity;
				if (((previousValue != value) 
							|| (this._tblDoDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDoDung.Entity = null;
						previousValue.tblChiTietPhieus.Remove(this);
					}
					this._tblDoDung.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieus.Add(this);
						this._IDDoDung = value.IDDoDung;
					}
					else
					{
						this._IDDoDung = default(int);
					}
					this.SendPropertyChanged("tblDoDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhong_tblChiTietPhieu", Storage="_tblPhong", ThisKey="IDPhong", OtherKey="IDPhong", IsForeignKey=true)]
		public tblPhong tblPhong
		{
			get
			{
				return this._tblPhong.Entity;
			}
			set
			{
				tblPhong previousValue = this._tblPhong.Entity;
				if (((previousValue != value) 
							|| (this._tblPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPhong.Entity = null;
						previousValue.tblChiTietPhieus.Remove(this);
					}
					this._tblPhong.Entity = value;
					if ((value != null))
					{
						value.tblChiTietPhieus.Add(this);
						this._IDPhong = value.IDPhong;
					}
					else
					{
						this._IDPhong = default(int);
					}
					this.SendPropertyChanged("tblPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDichVu")]
	public partial class tblDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDichVu;
		
		private string _TenDichVu;
		
		private System.Nullable<int> _GiaThanh;
		
		private EntitySet<tblChiTietPhieu> _tblChiTietPhieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDichVuChanging(int value);
    partial void OnIDDichVuChanged();
    partial void OnTenDichVuChanging(string value);
    partial void OnTenDichVuChanged();
    partial void OnGiaThanhChanging(System.Nullable<int> value);
    partial void OnGiaThanhChanged();
    #endregion
		
		public tblDichVu()
		{
			this._tblChiTietPhieus = new EntitySet<tblChiTietPhieu>(new Action<tblChiTietPhieu>(this.attach_tblChiTietPhieus), new Action<tblChiTietPhieu>(this.detach_tblChiTietPhieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDichVu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDichVu
		{
			get
			{
				return this._IDDichVu;
			}
			set
			{
				if ((this._IDDichVu != value))
				{
					this.OnIDDichVuChanging(value);
					this.SendPropertyChanging();
					this._IDDichVu = value;
					this.SendPropertyChanged("IDDichVu");
					this.OnIDDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDichVu", DbType="NVarChar(50)")]
		public string TenDichVu
		{
			get
			{
				return this._TenDichVu;
			}
			set
			{
				if ((this._TenDichVu != value))
				{
					this.OnTenDichVuChanging(value);
					this.SendPropertyChanging();
					this._TenDichVu = value;
					this.SendPropertyChanged("TenDichVu");
					this.OnTenDichVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaThanh", DbType="Int")]
		public System.Nullable<int> GiaThanh
		{
			get
			{
				return this._GiaThanh;
			}
			set
			{
				if ((this._GiaThanh != value))
				{
					this.OnGiaThanhChanging(value);
					this.SendPropertyChanging();
					this._GiaThanh = value;
					this.SendPropertyChanged("GiaThanh");
					this.OnGiaThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDichVu_tblChiTietPhieu", Storage="_tblChiTietPhieus", ThisKey="IDDichVu", OtherKey="IDDichVu")]
		public EntitySet<tblChiTietPhieu> tblChiTietPhieus
		{
			get
			{
				return this._tblChiTietPhieus;
			}
			set
			{
				this._tblChiTietPhieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieus(tblChiTietPhieu entity)
		{
			this.SendPropertyChanging();
			entity.tblDichVu = this;
		}
		
		private void detach_tblChiTietPhieus(tblChiTietPhieu entity)
		{
			this.SendPropertyChanging();
			entity.tblDichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDoDung")]
	public partial class tblDoDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDoDung;
		
		private string _TenDoDung;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<int> _DonGia;
		
		private EntitySet<tblChiTietPhieu> _tblChiTietPhieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDoDungChanging(int value);
    partial void OnIDDoDungChanged();
    partial void OnTenDoDungChanging(string value);
    partial void OnTenDoDungChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<int> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public tblDoDung()
		{
			this._tblChiTietPhieus = new EntitySet<tblChiTietPhieu>(new Action<tblChiTietPhieu>(this.attach_tblChiTietPhieus), new Action<tblChiTietPhieu>(this.detach_tblChiTietPhieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDoDung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDoDung
		{
			get
			{
				return this._IDDoDung;
			}
			set
			{
				if ((this._IDDoDung != value))
				{
					this.OnIDDoDungChanging(value);
					this.SendPropertyChanging();
					this._IDDoDung = value;
					this.SendPropertyChanged("IDDoDung");
					this.OnIDDoDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoDung", DbType="NVarChar(50)")]
		public string TenDoDung
		{
			get
			{
				return this._TenDoDung;
			}
			set
			{
				if ((this._TenDoDung != value))
				{
					this.OnTenDoDungChanging(value);
					this.SendPropertyChanging();
					this._TenDoDung = value;
					this.SendPropertyChanged("TenDoDung");
					this.OnTenDoDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int")]
		public System.Nullable<int> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDoDung_tblChiTietPhieu", Storage="_tblChiTietPhieus", ThisKey="IDDoDung", OtherKey="IDDoDung")]
		public EntitySet<tblChiTietPhieu> tblChiTietPhieus
		{
			get
			{
				return this._tblChiTietPhieus;
			}
			set
			{
				this._tblChiTietPhieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieus(tblChiTietPhieu entity)
		{
			this.SendPropertyChanging();
			entity.tblDoDung = this;
		}
		
		private void detach_tblChiTietPhieus(tblChiTietPhieu entity)
		{
			this.SendPropertyChanging();
			entity.tblDoDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKhach")]
	public partial class tblKhach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDKhach;
		
		private string _TenKhach;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<int> _SoNguoi;
		
		private EntitySet<tblPhieuThue> _tblPhieuThues;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKhachChanging(int value);
    partial void OnIDKhachChanged();
    partial void OnTenKhachChanging(string value);
    partial void OnTenKhachChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnSoNguoiChanging(System.Nullable<int> value);
    partial void OnSoNguoiChanged();
    #endregion
		
		public tblKhach()
		{
			this._tblPhieuThues = new EntitySet<tblPhieuThue>(new Action<tblPhieuThue>(this.attach_tblPhieuThues), new Action<tblPhieuThue>(this.detach_tblPhieuThues));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKhach", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDKhach
		{
			get
			{
				return this._IDKhach;
			}
			set
			{
				if ((this._IDKhach != value))
				{
					this.OnIDKhachChanging(value);
					this.SendPropertyChanging();
					this._IDKhach = value;
					this.SendPropertyChanged("IDKhach");
					this.OnIDKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhach", DbType="NVarChar(50)")]
		public string TenKhach
		{
			get
			{
				return this._TenKhach;
			}
			set
			{
				if ((this._TenKhach != value))
				{
					this.OnTenKhachChanging(value);
					this.SendPropertyChanging();
					this._TenKhach = value;
					this.SendPropertyChanged("TenKhach");
					this.OnTenKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NChar(20)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNguoi", DbType="Int")]
		public System.Nullable<int> SoNguoi
		{
			get
			{
				return this._SoNguoi;
			}
			set
			{
				if ((this._SoNguoi != value))
				{
					this.OnSoNguoiChanging(value);
					this.SendPropertyChanging();
					this._SoNguoi = value;
					this.SendPropertyChanged("SoNguoi");
					this.OnSoNguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhach_tblPhieuThue", Storage="_tblPhieuThues", ThisKey="IDKhach", OtherKey="IDKhach")]
		public EntitySet<tblPhieuThue> tblPhieuThues
		{
			get
			{
				return this._tblPhieuThues;
			}
			set
			{
				this._tblPhieuThues.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblPhieuThues(tblPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblKhach = this;
		}
		
		private void detach_tblPhieuThues(tblPhieuThue entity)
		{
			this.SendPropertyChanging();
			entity.tblKhach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhieuThue")]
	public partial class tblPhieuThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPhieuThue;
		
		private int _IDKhach;
		
		private System.Nullable<System.DateTime> _ThoiGianThue;
		
		private System.Nullable<System.DateTime> _ThoiGianTra;
		
		private System.Nullable<int> _TongTien;
		
		private EntityRef<tblKhach> _tblKhach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPhieuThueChanging(int value);
    partial void OnIDPhieuThueChanged();
    partial void OnIDKhachChanging(int value);
    partial void OnIDKhachChanged();
    partial void OnThoiGianThueChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianThueChanged();
    partial void OnThoiGianTraChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianTraChanged();
    partial void OnTongTienChanging(System.Nullable<int> value);
    partial void OnTongTienChanged();
    #endregion
		
		public tblPhieuThue()
		{
			this._tblKhach = default(EntityRef<tblKhach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhieuThue", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPhieuThue
		{
			get
			{
				return this._IDPhieuThue;
			}
			set
			{
				if ((this._IDPhieuThue != value))
				{
					this.OnIDPhieuThueChanging(value);
					this.SendPropertyChanging();
					this._IDPhieuThue = value;
					this.SendPropertyChanged("IDPhieuThue");
					this.OnIDPhieuThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKhach", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDKhach
		{
			get
			{
				return this._IDKhach;
			}
			set
			{
				if ((this._IDKhach != value))
				{
					if (this._tblKhach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKhachChanging(value);
					this.SendPropertyChanging();
					this._IDKhach = value;
					this.SendPropertyChanged("IDKhach");
					this.OnIDKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianThue", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianThue
		{
			get
			{
				return this._ThoiGianThue;
			}
			set
			{
				if ((this._ThoiGianThue != value))
				{
					this.OnThoiGianThueChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianThue = value;
					this.SendPropertyChanged("ThoiGianThue");
					this.OnThoiGianThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianTra", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianTra
		{
			get
			{
				return this._ThoiGianTra;
			}
			set
			{
				if ((this._ThoiGianTra != value))
				{
					this.OnThoiGianTraChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianTra = value;
					this.SendPropertyChanged("ThoiGianTra");
					this.OnThoiGianTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Int")]
		public System.Nullable<int> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhach_tblPhieuThue", Storage="_tblKhach", ThisKey="IDKhach", OtherKey="IDKhach", IsForeignKey=true)]
		public tblKhach tblKhach
		{
			get
			{
				return this._tblKhach.Entity;
			}
			set
			{
				tblKhach previousValue = this._tblKhach.Entity;
				if (((previousValue != value) 
							|| (this._tblKhach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhach.Entity = null;
						previousValue.tblPhieuThues.Remove(this);
					}
					this._tblKhach.Entity = value;
					if ((value != null))
					{
						value.tblPhieuThues.Add(this);
						this._IDKhach = value.IDKhach;
					}
					else
					{
						this._IDKhach = default(int);
					}
					this.SendPropertyChanged("tblKhach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPhong")]
	public partial class tblPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPhong;
		
		private System.Nullable<int> _SucChua;
		
		private System.Nullable<int> _GiaPhong;
		
		private string _TrangThai;
		
		private EntitySet<tblChiTietPhieu> _tblChiTietPhieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPhongChanging(int value);
    partial void OnIDPhongChanged();
    partial void OnSucChuaChanging(System.Nullable<int> value);
    partial void OnSucChuaChanged();
    partial void OnGiaPhongChanging(System.Nullable<int> value);
    partial void OnGiaPhongChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public tblPhong()
		{
			this._tblChiTietPhieus = new EntitySet<tblChiTietPhieu>(new Action<tblChiTietPhieu>(this.attach_tblChiTietPhieus), new Action<tblChiTietPhieu>(this.detach_tblChiTietPhieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPhong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPhong
		{
			get
			{
				return this._IDPhong;
			}
			set
			{
				if ((this._IDPhong != value))
				{
					this.OnIDPhongChanging(value);
					this.SendPropertyChanging();
					this._IDPhong = value;
					this.SendPropertyChanged("IDPhong");
					this.OnIDPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SucChua", DbType="Int")]
		public System.Nullable<int> SucChua
		{
			get
			{
				return this._SucChua;
			}
			set
			{
				if ((this._SucChua != value))
				{
					this.OnSucChuaChanging(value);
					this.SendPropertyChanging();
					this._SucChua = value;
					this.SendPropertyChanged("SucChua");
					this.OnSucChuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaPhong", DbType="Int")]
		public System.Nullable<int> GiaPhong
		{
			get
			{
				return this._GiaPhong;
			}
			set
			{
				if ((this._GiaPhong != value))
				{
					this.OnGiaPhongChanging(value);
					this.SendPropertyChanging();
					this._GiaPhong = value;
					this.SendPropertyChanged("GiaPhong");
					this.OnGiaPhongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblPhong_tblChiTietPhieu", Storage="_tblChiTietPhieus", ThisKey="IDPhong", OtherKey="IDPhong")]
		public EntitySet<tblChiTietPhieu> tblChiTietPhieus
		{
			get
			{
				return this._tblChiTietPhieus;
			}
			set
			{
				this._tblChiTietPhieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietPhieus(tblChiTietPhieu entity)
		{
			this.SendPropertyChanging();
			entity.tblPhong = this;
		}
		
		private void detach_tblChiTietPhieus(tblChiTietPhieu entity)
		{
			this.SendPropertyChanging();
			entity.tblPhong = null;
		}
	}
}
#pragma warning restore 1591
